scrapersite/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^article/(?P<slug>[\w-]+)/$', views.individual_post, name='detail'),
    url(r'^sports-news/$',views.sports_section,name='sports_section'),
    url(r'^world-news/$',views.worldNews_section,name='worldNews_section'),
    url(r'^india-news/$',views.indiaNews_section,name='indiaNews_section'),
    url(r'^entertainment-movies-news/$',views.movies_section,name='movies_section'),
    url(r'^science-tech/$',views.scienceandtech_section,name='scienceandtech_section'),

]

scrapersite/scrapersite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^home/', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    ]

scrapersite/home/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save
from home.articleProcess import *
from django.utils.text import slugify
from random import randint
from home.tweetsim import *
from home.tweets import *
# Create your models here.

class Post(models.Model):
    category_choices = (('0', 'Sports'), ('2', 'World-News'), ('1', 'India-News'), ('3', 'Entertainment and Movies'),
                        ('5', 'Uncategorized'), ('4', 'Science and Technology'))
    headline = models.CharField(max_length=500)
    body = models.TextField()
    pub_date = models.DateTimeField()
    category = models.CharField(max_length=100, choices=category_choices, default='4')
    headslug = models.SlugField()
    source = models.CharField(max_length=500, null=True, blank=True)
    summary = models.CharField(max_length=1000, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.headslug:
            ranin = randint(0, 1000)
            self.headslug = slugify(self.headline[:45] + str(ranin))
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.headline[:50]


class Tags(models.Model):
    posttag = models.ForeignKey(Post)
    tag = models.CharField(max_length=10)

class Tweets(models.Model):
    emotion_choices = (('-1','Negative'),('0','Neutral'),('1','Positive'))
    posttweet = models.ForeignKey(Post)
    tweet = models.CharField(max_length=400)
    emotion = models.CharField(max_length= 50,choices = emotion_choices)
    relavent = models.FloatField()
#def save_tweets(sender, instance, created, *args, **kwargs):
#    if created:
#        try:
#            tweets = find_tweets(instance.tag)
#            print(tweets)
#            for n, i in enumerate(tweets):
#                name = eval('"tweet"+str(n)')
#                name = Tweets(posttweet=instance.posttag, tweet=str(i))
#                name.emotion = '0'
#                name.relavent = sim(str(instance.posttag.headline),str(i))
#                name.save()
#        except Exception as e:
#            print(str(e))
#
#
#post_save.connect(save_tweets, sender=Tags)


def save_tags(sender, instance, created, *args, **kwargs):
    if created:
        tags = find_tags(instance.body)
        for n, i in enumerate(tags):
            name = eval('"tag"+str(n)')
            name = Tags(posttag=instance, tag=str(i))
            name.save()


post_save.connect(save_tags, sender=Post)


def save_category(sender, instance, *args, **kwargs):
    fet = sample_to_features(instance.body)

    category = predict_category(fet)
    print(category)
    if category == 0:
        instance.category = '0'
    elif category == 1:
        instance.category = '1'
    elif category == 2:
        instance.category = '2'
    elif category == 3:
        instance.category = '4'
    elif category == 4:
        instance.category = '3'
    else:
        instance.category = '5'


pre_save.connect(save_category, sender=Post)

scrapersite/home/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from .models import Post
from django.utils import timezone
from home.articleProcess import *
from home.allinonescraper import *
from home.tweetsim import *
from home.tweets import *
from threading import Thread
from home.updateTweets import *
import threading
from multiprocessing import Queue
# Create your views here.

def index(request):
    at_home = True
    posts = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    websites = {}
    try:
        po = paginator.page(page)
    except PageNotAnInteger:
        po = paginator.page(1)
    except EmptyPage:
        po = paginator.page(paginator.num_pages)
    context = {'posts': po,'page':page, 'at_home': at_home}
    # add_post()
    #start_posting()
    return render(request, 'home/home.html', context)


def individual_post(request, slug):
    p = get_object_or_404(Post, headslug=slug)
    website = add_website()
    for i in website.keys():
        #start_posting(i,website[i]['Append_url'],website[i]['headDiv'],website[i]['headName'],website[i]['bodyDiv'],website[i]['bodyName'])
        #print(website[i],website[i]['Append_url'],website[i]['headDiv'],website[i]['headName'],website[i]['bodyDiv'],website[i]['bodyName'])
        print(i)


        context = {'post': p}
    return render(request, 'home/detail.html', context)


def sports_section(request):
    at_sports = True
    sports_articles = Post.objects.filter(category='0').order_by('-pub_date')
    context = {'sports_articles': sports_articles, 'at_sports': at_sports}
    return render(request, 'home/sports_section.html', context)


def worldNews_section(request):
    at_worldNews = True
    worldNews_articles = Post.objects.filter(category='2').order_by('-pub_date')
    context = {'worldNews_articles': worldNews_articles, 'at_worldNews': at_worldNews}
    return render(request, 'home/worldNews_section.html', context)


def indiaNews_section(request):
    at_indiaNews = True
    indiaNews_articles = Post.objects.filter(category='1').order_by('-pub_date')
    paginator = Paginator(indiaNews_articles, 5)
    pa = request.GET.get('indNew')
    try:
        po = paginator.page(pa)
    except PageNotAnInteger:
        po = paginator.page(1)
    except EmptyPage:
        po = paginator.page(paginator.num_pages)
    context = {'posts': po,'page':pa, 'at_indiaNews': at_indiaNews}
    return render(request, 'home/indiaNews_section.html', context)


def movies_section(request):
    at_movies = True
    movies_articles = Post.objects.filter(category='3').order_by('-pub_date')
    context = {'movies_articles': movies_articles, 'at_movies': at_movies}
    return render(request, 'home/movies_section.html', context)
def scienceandtech_section(request):
    at_scienceandtech = True
    scienceandtech_articles = Post.objects.filter(category='4').order_by('-pub_date')
    context = {'scienceTech_articles': scienceandtech_articles, 'at_scienceandtech': at_scienceandtech}
    return render(request, 'home/scienceandtech_section.html', context)

def add_website():
    website ={}
    website['http://zeenews.india.com/'] = {'Append_url':
                                            'http://zeenews.india.com','headDiv':'class','headName':'article-heading'
                                            ,
                                            'bodyDiv':'class','bodyName':'field-items'}
    website['http://www.ndtv.com/'] = {'Append_url':'http://www.ndtv.com','headDiv':'itemprop','headName':'headline','bodyDiv':'itemprop','bodyName':'articleBody'}
    #website['http://www.bbc.com/'] ={'Append_url':'http://www.bbc.com','headDiv':'class','headName':'story-body__h1','bodyDiv':'class','bodyName':'story-body'}
    return website
    

scrapersite/home/templates/home/base.html
<html>
	<head>
	
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	</head>

<body>
	<ul class="nav nav-tabs">
		<li role="presentation" class="{%if at_home %}active{%endif%}"><a href="{% url 'home:index' %}">New and Trending</a></li>
<li role="presentation" class="{%if at_worldNews %}active  {%endif%}"><a href="{% url 'home:worldNews_section' %}">World </a></li>
<li role="presentation" class="{%if at_indiaNews %}active {%endif%}"><a href="{% url 'home:indiaNews_section' %}">India</a></li>
<li role="presentation" class="{%if at_sports %} active {%endif%}"><a href="{% url 'home:sports_section' %}">Sports</a></li>
<li role="presentation" class="{%if at_movies %} active {%endif%}"><a href="{% url 'home:movies_section' %}">Entertainment and Movies</a></li>
<li role="presentation" class="{%if at_scienceandtech %} active {%endif%}"><a href="{% url 'home:scienceandtech_section' %}">Science and Technology</a></li>



	</ul>
	{%block content%}

	{%endblock content%}

</body>

</html>

scrapersite/home/templates/home/detail.html
{% extends 'home/base.html' %}
<html>
	<head>
		<title>{{post.headslug}}</title>
	</head>
	<body>

		{%block content%}
		<div class="content col-md-10">
		<div class="col-md-offset-1">
		<h1 align= center>{{post.headline}}</h1>
		<h3 align = center> {{post.pub_date}}</h3>
		<p align = center> {{post.body}}</p>

		</div>
		<h3 align="center"> Related Tweets: </h3>
			{%for tw in post.tweets_set.all %}
		<div class="col-md-offset-1">
			{{tw.tweet}}
		</div>
		{%endfor%}
		</div>
				{%endblock content %}
	</body>
	

</html>

scrapersite/home/templates/home/home.html
{% extends 'home/base.html' %}
<html>
	<head>
		<title> Bodhi.AI home page </title>
	</head>

	<body>
		{%block content%}
	
		<h1 align='center'>All Posts</h1>
		{% for i in posts %}
		<div class="container">
		<div class = 'row col-md-10 col-md-offset-1'>
			
<a href="{% url 'home:detail' i.headslug %}">
	<div class="page-header">
  <h2>{{i.headline}}<div style="text-align: center;"> <small>Category : {{i.get_category_display}}<br>{{i.pub_date}}</small></div></h2>
</div></a>
		
		<div class="well" style="background: rgb(247, 249, 255);"><br> {{i.summary}}</div>
		<p align='center'></p>
		<p align='center'> Source: {{i.source}}</p>
		<p align= 'center'>Tags:</p>
		{%for tag in i.tags_set.all %}
				
		<div class = 'text-center'style= 'display:inline-block;float:center;text-align:center;position:relative;left:30%;'>
			 <li class="list-group-item">
  
    {{tag.tag}}
  </li>
</ul>
			</div>	
	
		{% endfor %}
		<br><br>
		</div>

		{%endfor%}	

<div class="pagination">
    <span class="step-links">


		<nav aria-label="Page navigation">
		  <ul class="pagination">
		  {% if posts.has_previous %}
		    <li>
		      <a href="?page={{ posts.previous_page_number }}" aria-label="Previous">
		        <span aria-hidden="true">&laquo;</span>
		      </a>
		    </li>
		    {% endif %}
		    <li>

		      
		    <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

		    </li>
		    
		      {% if posts.has_next %}
		    <li>
		      <a href="?page={{ posts.next_page_number }}" aria-label="Next">
		        <span aria-hidden="true">&raquo;</span>
		      </a>
		    </li>
		    {% endif %}
		  </ul>
		</nav>


        
       

       

      
        
        
    </span>
</div>



</div>	
			{%endblock content%}
	</body>
</html>

scrapersite/home/templates/home/indiaNews_section.html
{% extends 'home/base.html' %}
<html>
	<head>
		<title> India News </title>
	</head>

	<body>
		{%block content%}
	
		<h1 align='center'>India News</h1>
		{% for i in posts %}
		<div class="container">
		<div class = 'row col-md-10 col-md-offset-1'>
			
<a href="{% url 'home:detail' i.headslug %}"><div class="page-header" style="text-align: center;">
  <h2>{{i.headline}}<div style="text-align: center;"> <small><br>{{i.pub_date}}<br><br> Summary: </small></div></h2>
</div></a>
		
		<div class="well" style="background: rgb(247, 249, 255);"><br> {{i.summary}}</div>
		<p align='center'></p>
		<p align='center'> Source: {{i.source}}</p>
		<p align= 'center'>Tags:</p>
		{%for tag in i.tags_set.all %}
				
		<div class = 'text-center'style= 'display:inline-block;float:center;text-align:center;position:relative;left:30%;'>
			  <li class="list-group-item">
  
    {{tag.tag}}
  </li>
</ul>
			</div>	
	
		{% endfor %}
		<br><br>
		</div>

		{%endfor%}	

<div class="pagination">
    <span class="step-links">


		<nav aria-label="Page navigation">
		  <ul class="pagination">
		  {% if posts.has_previous %}
		    <li>
		      <a href="?indNew={{ posts.previous_page_number }}" aria-label="Previous">
		        <span aria-hidden="true">&laquo;</span>
		      </a>
		    </li>
		    {% endif %}
		    <li>

		      
		    <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

		    </li>
		    
		      {% if posts.has_next %}
		    <li>
		      <a href="?indNew={{ posts.next_page_number }}" aria-label="Next">
		        <span aria-hidden="true">&raquo;</span>
		      </a>
		    </li>
		    {% endif %}
		  </ul>
		</nav>           
    </span>
</div>



</div>	
			{%endblock content%}
	</body>
</html>

scrapersite/home/templates/home/movies_section.html
{% extends 'home/base.html' %}
<html>
	<head>
		<title> Entertainment and Movies </title>
	</head>
	<body>
		{% block content %}
		<h1 class='text-center'>Entertainment and Movies </h1>
					{% for article in movies_articles %}
			<div class='row col-md-8 col-md-offset-2'>

				<a href="{% url 'home:detail' article.headslug %}"><h3 align='center'>{{article.headline}}</h3></a>
			<p align='center'>{{article.pub_date}}</p>
			<p align='center'>{{article.summary}}</p>
			<p align='center'>Source: {{article.source}}</p>
			<p align='center'> Tags:</p>
			{% for tag in article.tags_set.all %}
<div class= 'text-center' style='display:inline-block;float:center;text-align:cetner;position:relative;left:40%;'>
				{ {{tag.tag}} }
			</div>
			{%endfor%}
		</div>
		{%endfor%}
		{%endblock%}
	</body>
</html>

scrapersite/home/templates/home/scienceandtech_section.html
{% extends 'home/base.html' %}
<html>
	<head>
		<title> Science and Technology Articles </title>
	</head>
	<body>
		{% block content %}
		<h1 class='text-center'> Science and Technology </h1>
					{% for article in scienceTech_articles %}
			<div class='row col-md-8 col-md-offset-2'>

				<a href="{% url 'home:detail' article.headslug %}"><h3 align='center'>{{article.headline}}</h3></a>
			<p align='center'>{{article.pub_date}}</p>
			<p align='center'>{{article.summary}}</p>
			<p align='center'>Source: {{article.source}}</p>
			<p align='center'> Tags:</p>
			{% for tag in article.tags_set.all %}
<div class= 'text-center' style='display:inline-block;float:center;text-align:center;position:relative;left:40%;'>
				{ {{tag.tag}} }
			</div>
			{%endfor%}
		</div>
		{%endfor%}
		{%endblock%}
	</body>
</html>

scrapersite/home/templates/home/sports_section.html
{% extends 'home/base.html' %}
<html>
	<head>
		<title> All Sports Articles </title>
	</head>
	<body>
		{% block content %}
		<h1 class='text-center'>Sports Articles </h1>
					{% for article in sports_articles %}
			<div class='row col-md-8 col-md-offset-2'>

				<a href="{% url 'home:detail' article.headslug %}"><h3 align='center'>{{article.headline}}</h3></a>
			<p align='center'>{{article.pub_date}}</p>
			<p align='center'>{{article.summary}}</p>
			<p align='center'>Source: {{article.source}}</p>
			<p align='center'> Tags:</p>
			{% for tag in article.tags_set.all %}
<div class= 'text-center' style='display:inline-block;float:center;text-align:cetner;position:relative;left:40%;'>
				{ {{tag.tag}} }
			</div>
			{%endfor%}
		</div>
		{%endfor%}
		{%endblock%}
	</body>
</html>

scrapersite/home/templates/home/worldNews_section.html
{% extends 'home/base.html' %}
<html>
	<head>
		<title> World Related Articles </title>
	</head>
	<body>
		{% block content %}
		<h1 class='text-center'> World Articles </h1>
					{% for article in worldNews_articles %}
			<div class='row col-md-8 col-md-offset-2'>

				<a href="{% url 'home:detail' article.headslug %}"><h3 align='center'>{{article.headline}}</h3></a>
			<p align='center'>{{article.pub_date}}</p>
			<p align='center'>{{article.summary}}</p>
			<p align='center'>Source: {{article.source}}</p>
			<p align='center'> Tags:</p>
			{% for tag in article.tags_set.all %}
<div class= 'text-center' style='display:inline-block;float:center;text-align:cetner;position:relative;left:40%;'>
				{ {{tag.tag}} }
			</div>
			{%endfor%}
		</div>
		{%endfor%}
		{%endblock%}
	</body>
</html>